In [2]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 16.9 MB/s eta 0:00:00m eta 0:00:010:00:01


In [3]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 15.3 MB/s eta 0:00:000:00:01 eta 0:00:01


In [4]:
import numpy as np

In [5]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [7]:
a = np.array(a)
a

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.ndim

2

In [10]:
a.shape

(3, 3)

In [11]:
a.size

9

In [12]:
a[2][2]

np.int64(33)

In [13]:
a[2, 2]

np.int64(33)

In [14]:
a[0][:2]

array([11, 12])

In [15]:
a[:2, 2]

array([13, 23])

In [17]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [3, 4]])

In [18]:
z = x + y
z

array([[2, 4],
       [6, 8]])

In [19]:
z = 2 * z
z

array([[ 4,  8],
       [12, 16]])

In [20]:
z = x * y
z

array([[ 1,  4],
       [ 9, 16]])

In [21]:
z = np.dot(x, y)
z

array([[ 7, 10],
       [15, 22]])

In [22]:
z = np.sin(z)
z

array([[ 0.6569866 , -0.54402111],
       [ 0.65028784, -0.00885131]])

In [23]:
z.T


array([[ 0.6569866 ,  0.65028784],
       [-0.54402111, -0.00885131]])

In [26]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
x.shape

(3, 2)

In [28]:
x.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])